# Generated by Django 4.2.11 on 2024-03-07 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('paid_training_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('pool_type', models.CharField(choices=[('1', 'Большой бассейн'), ('2', 'Малый бассейн')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('children', models.ManyToManyField(to='backend.child')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.trainers')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
    ]
