# Generated by Django 4.2.11 on 2024-03-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Фио ребёнка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='paid_training_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во оплаченных занятий'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Фио тренера'),
        ),
        migrations.AlterField(
            model_name='training',
            name='children',
            field=models.ManyToManyField(to='backend.child', verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка для поста (не обязательно)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='pool_type',
            field=models.CharField(choices=[('1', 'Большой бассейн'), ('2', 'Малый бассейн')], max_length=255, verbose_name='Тип бассейна'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.trainers', verbose_name='Тренер'),
        ),
    ]
