# Generated by Django 4.2.11 on 2024-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_child_name_alter_child_paid_training_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Closed')], default='Closed', max_length=255),
        ),
    ]
