# Generated by Django 4.2.11 on 2024-03-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_training_training_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Айди чата родителя'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Closed')], default='Closed', max_length=255, verbose_name='Статус тренировки'),
        ),
    ]
