# Generated by Django 4.2.11 on 2024-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_child_parent_chat_id_alter_training_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255, verbose_name='Имя ребенка')),
                ('current_id', models.IntegerField(verbose_name='Нынешний айди')),
            ],
        ),
    ]
