# Generated by Django 4.2.11 on 2024-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_childid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childid',
            name='child_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя ребенка'),
        ),
    ]
