# Generated by Django 4.2.11 on 2024-03-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_childid_child_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childid',
            old_name='child_name',
            new_name='name',
        ),
    ]
