# Generated by Django 4.2.11 on 2024-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_current_id_childid_parent_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childid',
            name='parent_chat_id',
            field=models.IntegerField(unique=True, verbose_name='Нынешний айди'),
        ),
    ]
