# Generated by Django 4.2.11 on 2024-03-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_training_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='image',
        ),
    ]
