# Generated by Django 4.2.11 on 2024-03-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_training_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('child_name', models.CharField(max_length=255, verbose_name='ФИО ребенка')),
                ('add_trainings_count', models.IntegerField(verbose_name='Добавленные тренировки')),
            ],
        ),
    ]
