# Generated by Django 4.2.11 on 2024-04-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_trainers_city_trainers_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_balance_update',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего пополнения'),
        ),
    ]
