# Generated by Django 4.2.11 on 2024-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_child_last_balance_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Айди чата родителя'),
        ),
        migrations.AlterField(
            model_name='childid',
            name='parent_chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Нынешний айди'),
        ),
    ]
