# Generated by Django 4.2.11 on 2024-11-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_child_parent_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='pool_type',
            field=models.CharField(choices=[('1', 'Большой бассейн 🐬'), ('2', 'Малый бассейн 🐠')], max_length=255, verbose_name='Тип бассейна'),
        ),
    ]
