# Generated by Django 4.2.11 on 2024-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_training_pool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='last_balance_update',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата последнего пополнения'),
        ),
    ]
