# Generated by Django 4.2.11 on 2024-11-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_child_last_balance_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание тренировки'),
        ),
    ]
