# Generated by Django 4.2.11 on 2024-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о тренере'),
        ),
    ]
